spring:

  main:
    allow-bean-definition-overriding: true
    web-application-type : reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/microservices
          jwk-set-uri: http://keycloak:8080/realms/microservices/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: bloc
          uri: lb://BLOCSERVICE
          predicates:
            - Path=/bloc/**
          filters:
            - name: RequestHeaderToRequestUri
              args:
                name: Authorization
        - id: node
          uri: http://localhost:5000
          predicates:
            - Path=/api/**
          filters:
            - name: RequestHeaderToRequestUri
              args:
                name: Authorization
        - id: chambre
          uri: lb://CHAMBRESERVICE
          predicates:
            - Path=/chambre/**
          filters:
            - name: RequestHeaderToRequestUri
              args:
                name: Authorization
        - id: etudiant
          uri: lb://ETUDIANTSERVICE
          predicates:
            - Path=/etudiant/**
          filters:
            - name: RequestHeaderToRequestUri
              args:
                name: Authorization
        - id: foyer
          uri: lb://FOYER
          predicates:
            - Path=/foyer/**
          filters:
            - name: RequestHeaderToRequestUri
              args:
                name: Authorization
        - id: reservation
          uri: lb://RESERVATION
          predicates:
            - Path=/reservation/**
          filters:
            - name: RequestHeaderToRequestUri
              args:
                name: Authorization
server:
  port: 8222



keycloak:
  server-url: http://keycloak:8080
  resource: gateway-client
  realm: microservices
  client-id: gateway-client
  client-secret: 0JjUfBvbz5yehMjgzdtC7TNEYDvfUkMG

