spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/microservices
          jwk-set-uri: http://keycloak:8080/realms/microservices/protocol/openid-connect/certs
  datasource:
      url: jdbc:h2:file:./chambreservice/data/chambredb_microservice
      driver-class-name: org.h2.Driver
      username: sa
      password:
  h2:
      console:
        enabled: true
        path: /h2-console  # http://localhost:8085/h2-console
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect



server:
  port: 8085

eureka:
  instance:
    hostname: discovery-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/


